# Generated by Django 6.0.7 on 2026-07-27 19:17

import app_hr.models
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد (شمسی)')),
                ('created_at_en', models.DateTimeField(auto_now_add=True, verbose_name='Created at (EN)')),
                ('updated_at_en', models.DateTimeField(auto_now=True, verbose_name='Updated at (EN)')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فراخوان')),
                ('position', models.CharField(max_length=200, verbose_name='عنوان شغلی')),
                ('activity', models.CharField(max_length=200, verbose_name='واحد / حوزه فعالیت')),
                ('min_age', models.PositiveSmallIntegerField(verbose_name='حداقل سن')),
                ('max_age', models.PositiveSmallIntegerField(verbose_name='حداکثر سن')),
                ('education_level', models.CharField(choices=[('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, verbose_name='حداقل مدرک تحصیلی')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('any', 'فرقی ندارد')], default='any', max_length=10, verbose_name='جنسیت')),
                ('military_status_required', models.CharField(blank=True, choices=[('completed', 'پایان خدمت'), ('exempt', 'بدون محدودیت درجذب')], max_length=20, null=True, verbose_name='وضعیت نظام وظیفه (ویژه آقایان)')),
                ('min_experience_years', models.PositiveSmallIntegerField(verbose_name='حداقل سابقه کار (سال)')),
                ('recruitment_status', models.CharField(choices=[('open', 'در حال جذب نیرو'), ('closed', 'اتمام جذب')], default='open', max_length=10, verbose_name='وضعیت جذب')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='اسلاگ')),
                ('poster', models.ImageField(upload_to='job_posters/', verbose_name='پوستر فراخوان')),
                ('description_1', models.TextField(verbose_name='توضیحات فراخوان')),
                ('description_2', models.TextField(verbose_name='مزایای شغلی')),
                ('start_date_fa', django_jalali.db.models.jDateField(verbose_name='تاریخ (شمسی)')),
                ('start_date_en', models.DateField(blank=True, editable=False, null=True, verbose_name='تاریخ  (میلادی)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'فراخوان جذب',
                'verbose_name_plural': 'فراخوان\u200cهای جذب',
                'ordering': ('-created_at_fa', 'ordering'),
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد (شمسی)')),
                ('created_at_en', models.DateTimeField(auto_now_add=True, verbose_name='Created at (EN)')),
                ('updated_at_en', models.DateTimeField(auto_now=True, verbose_name='Updated at (EN)')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='اسلاگ')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('age', models.PositiveSmallIntegerField(verbose_name='سن')),
                ('marital_status', models.CharField(choices=[('single', 'مجرد'), ('married', 'متأهل')], max_length=10, verbose_name='وضعیت تأهل')),
                ('military_status', models.CharField(blank=True, choices=[('completed', 'پایان خدمت'), ('exempt', 'معاف')], max_length=20, null=True, verbose_name='وضعیت نظام وظیفه')),
                ('mobile', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('mobile_support', models.CharField(max_length=20, verbose_name='شماره تماس ضروری')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیک')),
                ('resume_file', models.FileField(upload_to='resumes/', validators=[app_hr.models.validate_pdf_file], verbose_name='رزومه')),
                ('status', models.CharField(choices=[('reviewed', 'در حال بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی ارسال\u200cکننده')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app_hr.jobopportunity', verbose_name='فراخوان')),
            ],
            options={
                'verbose_name': 'درخواست جذب',
                'verbose_name_plural': 'درخواست\u200cهای جذب ارسال شده ',
                'ordering': ('-created_at_en',),
            },
        ),
    ]
