# Generated by Django 6.0.7 on 2026-08-30 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('unit', models.CharField(choices=[('PCS', 'عدد'), ('METER', 'متر'), ('KG', 'کیلوگرم'), ('BOX', 'جعبه'), ('PACK', 'بسته'), ('SET', 'ست')], default='PCS', max_length=20, verbose_name='واحد')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='حداقل موجودی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام انبار')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد انبار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='انباردار')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.PositiveBigIntegerField(verbose_name='شناسه درخواست')),
                ('request_number', models.CharField(max_length=50, verbose_name='شماره درخواست')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('AVAILABLE', 'موجود'), ('PARTIAL', 'کسری موجودی'), ('DELIVERED', 'تأیید و تحویل شد'), ('REJECTED', 'رد شد')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات انبار')),
                ('shortage_description', models.TextField(blank=True, verbose_name='شرح کسری')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_requests', to='erp_warehouse.warehouse', verbose_name='انبار')),
                ('warehouse_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_requests_managed', to=settings.AUTH_USER_MODEL, verbose_name='انباردار')),
            ],
            options={
                'verbose_name': 'درخواست انبار',
                'verbose_name_plural': 'درخواست\u200cهای انبار',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'ورود'), ('OUT', 'خروج'), ('RETURN', 'برگشت'), ('ADJUST', 'اصلاح موجودی')], max_length=20, verbose_name='نوع تراکنش')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مقدار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='erp_warehouse.product', verbose_name='کالا')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='erp_warehouse.warehouse', verbose_name='انبار')),
                ('warehouse_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='erp_warehouse.warehouserequest', verbose_name='درخواست انبار')),
            ],
            options={
                'verbose_name': 'گردش انبار',
                'verbose_name_plural': 'گردش انبار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مقدار درخواستی')),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مقدار موجود')),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مقدار تحویل شده')),
                ('shortage_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مقدار کسری')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_request_items', to='erp_warehouse.product', verbose_name='کالا')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_warehouse.warehouserequest', verbose_name='درخواست انبار')),
            ],
            options={
                'verbose_name': 'قلم درخواست انبار',
                'verbose_name_plural': 'اقلام درخواست انبار',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='موجودی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='erp_warehouse.product', verbose_name='کالا')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='erp_warehouse.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'موجودی',
                'verbose_name_plural': 'موجودی\u200cها',
                'ordering': ['product'],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'product'), name='unique_warehouse_product_stock')],
            },
        ),
    ]
