# Generated by Django 6.0.7 on 2026-08-30 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_execution', '0002_remove_executionrequest_request_id_and_more'),
        ('erp_warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'موجودی انبار', 'verbose_name_plural': 'موجودی انبارها'},
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'گردش انبار', 'verbose_name_plural': 'گردش انبارها'},
        ),
        migrations.AlterModelOptions(
            name='warehouserequestitem',
            options={'verbose_name': 'قلم درخواست انبار', 'verbose_name_plural': 'اقلام درخواست انبار'},
        ),
        migrations.RenameField(
            model_name='warehouserequestitem',
            old_name='request',
            new_name='warehouse_request',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='request_id',
        ),
        migrations.AddField(
            model_name='warehouserequest',
            name='execution',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_request', to='erp_execution.executionrequest', verbose_name='درخواست اجرایات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouserequest',
            name='project_name',
            field=models.CharField(default=1, max_length=200, verbose_name='نام پروژه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouserequestitem',
            name='execution_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_items', to='erp_execution.executionitem', verbose_name='قلم اجرایات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='عدد', max_length=30, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='erp_warehouse.warehouse', verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'ورود'), ('OUT', 'خروج'), ('ADJUSTMENT', 'اصلاح موجودی')], max_length=20, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='erp_warehouse.warehouse', verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='warehouse_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='erp_warehouse.warehouserequest', verbose_name='درخواست انبار'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='کد انبار'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='انباردار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام انبار'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت تحویل'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='شرح درخواست'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت درخواست'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده انبار'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت بررسی'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('AVAILABLE', 'موجود و تأیید شد'), ('PARTIAL', 'کسری موجودی'), ('DELIVERED', 'تحویل شد'), ('REJECTED', 'رد شد')], default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='erp_warehouse.warehouse', verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='warehouse_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_requests_managed', to=settings.AUTH_USER_MODEL, verbose_name='انباردار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouserequestitem',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='موجودی قابل تحویل'),
        ),
        migrations.AlterField(
            model_name='warehouserequestitem',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تعداد تحویل\u200cشده'),
        ),
        migrations.AlterField(
            model_name='warehouserequestitem',
            name='requested_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='تعداد درخواستی'),
        ),
        migrations.AlterField(
            model_name='warehouserequestitem',
            name='shortage_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تعداد کسری'),
        ),
        migrations.AddConstraint(
            model_name='warehouserequestitem',
            constraint=models.UniqueConstraint(fields=('warehouse_request', 'execution_item'), name='unique_warehouse_execution_item'),
        ),
    ]
