# Generated by Django 6.0.7 on 2026-08-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_warehouse', '0002_alter_stock_options_alter_stocktransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['warehouse', 'product'], 'verbose_name': 'موجودی انبار', 'verbose_name_plural': 'موجودی انبارها'},
        ),
        migrations.AlterModelOptions(
            name='warehouserequestitem',
            options={'ordering': ['warehouse_request', 'execution_item__item_number'], 'verbose_name': 'قلم درخواست انبار', 'verbose_name_plural': 'اقلام درخواست انبار'},
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='requested_by',
        ),
    ]
