# Generated by Django 6.0.7 on 2026-07-27 19:17

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی استعلام خرید',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای استعلام خرید',
                'ordering': ['-created_at_fa'],
            },
        ),
        migrations.CreateModel(
            name='InquiryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'برچسب استعلام خرید',
                'verbose_name_plural': 'برچسب\u200cهای استعلام خرید',
                'ordering': ['-created_at_fa'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('inquiry_number', models.CharField(max_length=100, unique=True, verbose_name='شماره استعلام')),
                ('start_date_fa', django_jalali.db.models.jDateField(help_text='1373-08-10', verbose_name='تاریخ شروع (شمسی)')),
                ('end_date_fa', django_jalali.db.models.jDateField(help_text='1373-08-10', verbose_name='تاریخ پایان (شمسی)')),
                ('start_date_en', models.DateField(verbose_name='تاریخ شروع (میلادی)')),
                ('end_date_en', models.DateField(verbose_name='تاریخ پایان (میلادی)')),
                ('cover_image', models.ImageField(upload_to='purchase/cover', verbose_name='تصویر')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='purchase/files', verbose_name='فایل پیوست')),
                ('estimated_amount', models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ برآوردی')),
                ('description_fa', models.TextField(verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(verbose_name='توضیحات انگلیسی')),
                ('status', models.CharField(choices=[('open', 'در حال برگزاری'), ('extended', 'تمدید شده'), ('closed', 'پایان یافته')], default='open', max_length=20, verbose_name='وضعیت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='app_inquiry.inquirycategory', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(blank=True, related_name='inquiries', to='app_inquiry.inquirytag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'استعلام خرید',
                'verbose_name_plural': 'استعلام\u200cهای خرید',
                'ordering': ['-created_at_fa'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInquiryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='purchase/gallery', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app_inquiry.purchaseinquiry', verbose_name='استعلام خرید')),
            ],
            options={
                'verbose_name': 'تصویر استعلام خرید',
                'verbose_name_plural': 'گالری تصاویر',
                'ordering': ('order',),
            },
        ),
    ]
