# Generated by Django 6.0.7 on 2026-07-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی (فارسی)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام و نام خانوادگی (انگلیسی)')),
                ('position_fa', models.CharField(max_length=200, verbose_name='سمت (فارسی)')),
                ('position_en', models.CharField(blank=True, max_length=200, verbose_name='سمت (انگلیسی)')),
                ('photo', models.ImageField(upload_to='org_photos/', verbose_name='عکس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب در زیرمجموعه')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('content_en', models.TextField(blank=True, verbose_name='متن انگلیسی')),
                ('content_fa', models.TextField(blank=True, verbose_name='متن فارسی')),
                ('is_ceo', models.BooleanField(default=False, verbose_name='رئیس هیأت\u200cمدیره')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app_chart.boardmember', verbose_name='والد / سرپرست')),
            ],
            options={
                'verbose_name': 'عضو هیأت\u200cمدیره',
                'verbose_name_plural': 'اعضای هیأت\u200cمدیره',
                'ordering': ['parent__id', 'order', 'name_fa'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی (فارسی)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام و نام خانوادگی (انگلیسی)')),
                ('position_fa', models.CharField(max_length=200, verbose_name='سمت (فارسی)')),
                ('position_en', models.CharField(blank=True, max_length=200, verbose_name='سمت (انگلیسی)')),
                ('photo', models.ImageField(upload_to='org_photos/', verbose_name='عکس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب در زیرمجموعه')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('content_en', models.TextField(blank=True, verbose_name='متن انگلیسی')),
                ('content_fa', models.TextField(blank=True, verbose_name='متن فارسی')),
                ('is_ceo', models.BooleanField(default=False, verbose_name='مدیرعامل')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app_chart.person', verbose_name='والد / سرپرست')),
            ],
            options={
                'verbose_name': 'چارت سازمانی',
                'verbose_name_plural': 'چارت سازمانی کلی',
                'ordering': ['parent__id', 'order', 'name_fa'],
            },
        ),
    ]
