# Generated by Django 5.2.8 on 2026-02-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='estimated_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ ضمانت مزایده'),
        ),
    ]
