# Generated by Django 6.0.7 on 2026-08-30 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد درخواست')),
                ('project_name', models.CharField(max_length=200, verbose_name='نام پروژه')),
                ('description', models.TextField(blank=True, verbose_name='شرح درخواست')),
                ('priority', models.CharField(choices=[('LOW', 'کم'), ('NORMAL', 'عادی'), ('HIGH', 'زیاد'), ('URGENT', 'فوری')], default='NORMAL', max_length=20, verbose_name='اولویت')),
                ('item_1', models.CharField(blank=True, max_length=255, verbose_name='مورد ۱')),
                ('quantity_1', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تعداد ۱')),
                ('item_2', models.CharField(blank=True, max_length=255, verbose_name='مورد ۲')),
                ('quantity_2', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تعداد ۲')),
                ('item_3', models.CharField(blank=True, max_length=255, verbose_name='مورد ۳')),
                ('quantity_3', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تعداد ۳')),
                ('item_4', models.CharField(blank=True, max_length=255, verbose_name='مورد ۴')),
                ('quantity_4', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تعداد ۴')),
                ('item_5', models.CharField(blank=True, max_length=255, verbose_name='مورد ۵')),
                ('quantity_5', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تعداد ۵')),
                ('status', models.CharField(choices=[('NEW', 'جدید'), ('SENT_TO_EXECUTION', 'ارسال شده به اجرایات'), ('IN_EXECUTION', 'در حال بررسی اجرایات'), ('SENT_TO_WAREHOUSE', 'ارسال شده به انبار'), ('IN_WAREHOUSE', 'در حال بررسی انبار'), ('WAITING_REQUESTER', 'در انتظار درخواست\u200cکننده'), ('COMPLETED_BY_REQUESTER', 'اتمام کار توسط درخواست\u200cکننده'), ('SENT_TO_FINANCE', 'ارسال شده به مالی'), ('INVOICED', 'فاکتور صادر شده'), ('COMPLETED', 'تکمیل نهایی'), ('REJECTED', 'رد شده'), ('CANCELLED', 'لغو شده')], default='NEW', max_length=30, verbose_name='وضعیت')),
                ('requester_note', models.TextField(blank=True, verbose_name='توضیحات درخواست\u200cکننده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت ثبت')),
                ('sent_to_execution_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت ارسال به اجرایات')),
                ('requester_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت اتمام توسط درخواست\u200cکننده')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت تکمیل نهایی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
