# Generated by Django 6.0.7 on 2026-08-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='requester',
        ),
    ]
