# Generated by Django 6.0.7 on 2026-08-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_requests', '0002_remove_request_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requester_note',
            field=models.TextField(blank=True, verbose_name='توضیحات درخواست'),
        ),
    ]
