# Generated by Django 6.0.7 on 2026-07-27 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gregorian_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='سال میلادی')),
                ('gregorian_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='ماه میلادی')),
                ('jalali_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1300)], verbose_name='سال شمسی')),
                ('jalali_month', models.PositiveSmallIntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='ماه شمسی')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ کل فروش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'گزارش فروش',
                'verbose_name_plural': 'گزارش\u200cهای فروش',
                'ordering': ('jalali_year', 'jalali_month'),
                'unique_together': {('gregorian_year', 'gregorian_month', 'jalali_year', 'jalali_month')},
            },
        ),
    ]
