# Generated by Django 6.0.7 on 2026-07-27 19:17

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته خبر',
                'verbose_name_plural': 'دسته\u200cهای خبر',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('summary_fa', models.TextField(verbose_name='متن قسمت اول فارسی')),
                ('summary_en', models.TextField(verbose_name='متن  قسمت اول انگلیسی')),
                ('content_fa', models.TextField(blank=True, verbose_name='متن قسمت دوم فارسی')),
                ('content_en', models.TextField(blank=True, verbose_name='متن قسمت دوم انگلیسی')),
                ('image', models.ImageField(upload_to='news/cover/', verbose_name='کاور خبر')),
                ('publish_date_fa', django_jalali.db.models.jDateField(help_text='1373-08-10', verbose_name='تاریخ انتشار (شمسی)')),
                ('publish_date_en', models.DateField(verbose_name='تاریخ انتشار (میلادی)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_special', models.BooleanField(default=False, verbose_name='خبر ویژه')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='منبع خبر')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='محل وقوع خبر')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_news.newscategory', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(related_name='news_tags', to='app_news.newstag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-publish_date_fa', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_news.news')),
            ],
            options={
                'verbose_name': 'تصویر خبر',
                'verbose_name_plural': 'عکس\u200cهای خبر',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='news/videos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح ویدیو')),
                ('duration', models.CharField(blank=True, max_length=10, null=True, verbose_name='مدت زمان ویدیو')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app_news.news')),
            ],
            options={
                'verbose_name': 'ویدیوی خبر',
                'verbose_name_plural': 'ویدیوهای خبر',
                'ordering': ['order', 'id'],
            },
        ),
    ]
