# Generated by Django 6.0.7 on 2026-07-17 13:45

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ('-created_at_fa', 'order'),
            },
        ),
        migrations.CreateModel(
            name='blog_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ('-created_at_fa', 'order'),
            },
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(default='blog/default.jpg', upload_to='blog/image', verbose_name='عکس اصلی')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='blog/upload_file', verbose_name='آپلود فایل')),
                ('content_1_fa', models.TextField(verbose_name='متن فارسی 1')),
                ('content_1_en', models.TextField(verbose_name='متن انگلیسی 1')),
                ('content_2_fa', models.TextField(blank=True, verbose_name='متن فارسی 2')),
                ('content_2_en', models.TextField(blank=True, verbose_name='متن انگلیسی 2')),
                ('publish_date_fa', django_jalali.db.models.jDateField(help_text='1373-08-10', verbose_name='تاریخ انتشار (شمسی)')),
                ('publish_date_en', models.DateField(verbose_name='تاریخ انتشار (میلادی)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='app_blog.blog_category', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog', to='app_blog.blog_tag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['order', '-publish_date_fa'],
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/gallery/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_blog.blog', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'تصویر مقاله',
                'verbose_name_plural': 'گالری',
                'ordering': ['order', 'id'],
            },
        ),
    ]
