# Generated by Django 5.2.15 on 2026-07-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date_fa',
            field=models.CharField(help_text='مثال: 1373-08-10', max_length=10, verbose_name='تاریخ انتشار (شمسی)'),
        ),
    ]
