# Generated by Django 5.2.15 on 2026-07-10 13:41

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_blog_publish_date_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date_fa',
            field=django_jalali.db.models.jDateField(help_text='1373-08-10', verbose_name='تاریخ انتشار (شمسی)'),
        ),
    ]
