# Generated by Django 6.0.7 on 2026-08-30 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.PositiveBigIntegerField(unique=True, verbose_name='شناسه درخواست')),
                ('request_number', models.CharField(max_length=50, verbose_name='شماره درخواست')),
                ('project_name', models.CharField(max_length=200, verbose_name='نام پروژه')),
                ('status', models.CharField(choices=[('NEW', 'جدید'), ('SEEN', 'دیده شد'), ('IN_PROGRESS', 'در حال اجرا'), ('WAITING_WAREHOUSE', 'در انتظار انبار'), ('COMPLETED', 'اجرایات تکمیل شد'), ('REJECTED', 'رد شد')], default='NEW', max_length=30, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='شرح اجرایات')),
                ('requester_description', models.TextField(blank=True, verbose_name='شرح درخواست\u200cکننده')),
                ('execution_description', models.TextField(blank=True, verbose_name='گزارش اجرایات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مشاهده')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع اجرا')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان اجرایات')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_requests', to=settings.AUTH_USER_MODEL, verbose_name='مجری')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست اجرایات',
                'verbose_name_plural': 'درخواست\u200cهای اجرایات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveSmallIntegerField(verbose_name='شماره قلم')),
                ('item_name', models.CharField(max_length=200, verbose_name='نام قلم')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='تعداد')),
                ('unit', models.CharField(default='عدد', max_length=30, verbose_name='واحد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_execution.executionrequest', verbose_name='درخواست اجرایات')),
            ],
            options={
                'verbose_name': 'قلم اجرایات',
                'verbose_name_plural': 'اقلام اجرایات',
                'ordering': ['item_number'],
                'constraints': [models.UniqueConstraint(fields=('execution', 'item_number'), name='unique_execution_item_number')],
            },
        ),
    ]
