# Generated by Django 6.0.7 on 2026-08-30 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_execution', '0001_initial'),
        ('erp_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionrequest',
            name='request_id',
        ),
        migrations.AddField(
            model_name='executionrequest',
            name='request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='execution_request', to='erp_requests.request', verbose_name='درخواست اصلی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت ارسال'),
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='شرح درخواست'),
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت مشاهده'),
        ),
    ]
