# Generated by Django 6.0.7 on 2026-08-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_execution', '0002_remove_executionrequest_request_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionrequest',
            name='requester',
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='requester_description',
            field=models.TextField(blank=True, verbose_name='شرح درخواست'),
        ),
    ]
