# Generated by Django 6.0.7 on 2026-07-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='banners/about/', verbose_name='تصویر اول')),
                ('image_2', models.ImageField(upload_to='banners/about/', verbose_name='تصویر دوم')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تصاویر درباره ما',
                'verbose_name_plural': 'تصاویر درباره ما',
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='اولویت نمایش')),
                ('label_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='برچسب (فارسی)')),
                ('title_p1_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان اول (فارسی)')),
                ('title_p2_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان دوم رنگ متفاوت (فارسی)')),
                ('title_p3_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سوم (فارسی)')),
                ('subtitle_fa', models.CharField(blank=True, max_length=500, null=True, verbose_name='زیرعنوان (فارسی)')),
                ('label_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='برچسب (انگلیسی)')),
                ('title_p1_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان اول (انگلیسی)')),
                ('title_p2_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان دوم رنگ متفاوت (انگلیسی)')),
                ('title_p3_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سوم (انگلیسی)')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='زیرعنوان (انگلیسی)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='banners/hero/', verbose_name='تصویر بنر')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'بنر های اصلی پوستر',
                'verbose_name_plural': 'بنر های اصلی پوستر ',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='HeroSliderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_slider', models.CharField(choices=[('hs_1', 'اسلایدر مدل ۱(کوچک،وسط)'), ('hs_2', 'اسلایدر مدل ۲(تمام صفحه)')], default='hs_1', max_length=10, verbose_name='مدل اسلایدر فعال صفحه اصلی')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات اسلایدر صفحه اصلی',
                'verbose_name_plural': 'تنظیمات اسلایدر صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='اولویت نمایش')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='banners/main/', verbose_name='تصویر بنر')),
                ('title_p1_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان اول (فارسی)')),
                ('title_p2_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان دوم (فارسی)')),
                ('subtitle_fa', models.CharField(blank=True, max_length=500, null=True, verbose_name='زیرعنوان (فارسی)')),
                ('title_p1_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان اول (انگلیسی)')),
                ('title_p2_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان دوم (انگلیسی)')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='زیرعنوان (انگلیسی)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'بنر داخلی',
                'verbose_name_plural': 'بنر داخلی',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='OtherBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='اولویت نمایش')),
                ('label_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان بنر')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='banners/other/', verbose_name='تصویر بنر')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'بنر هدرِ کل صفحات',
                'verbose_name_plural': 'بنر هدرِ کل',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SpecialProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان بنر')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='banners/special-products/', verbose_name='تصویر بنر')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='اولویت نمایش')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'بنر محصول ویژه',
                'verbose_name_plural': 'بنر محصولات ویژه',
                'ordering': ('order', 'created_at'),
            },
        ),
    ]
