# Generated by Django 6.0.7 on 2026-07-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(upload_to='banners/hero/', verbose_name='تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(upload_to='banners/main/', verbose_name='تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='otherbanner',
            name='image',
            field=models.ImageField(upload_to='banners/other/', verbose_name='تصویر بنر'),
        ),
    ]
