# Generated by Django 6.0.7 on 2026-07-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banner', '0003_aboutbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutbanner',
            options={'verbose_name': 'تصاویر درباره ما', 'verbose_name_plural': 'تصاویر درباره ما'},
        ),
        migrations.RemoveField(
            model_name='aboutbanner',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutbanner',
            name='image_1',
            field=models.ImageField(default=1, upload_to='banners/about/', verbose_name='تصویر اول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutbanner',
            name='image_2',
            field=models.ImageField(default=1, upload_to='banners/about/', verbose_name='تصویر دوم'),
            preserve_default=False,
        ),
    ]
