# Generated by Django 6.0.7 on 2026-07-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='نام فایل ZIP نسخه پشتیبان', max_length=255, unique=True, verbose_name='نام فایل')),
                ('file_size', models.PositiveBigIntegerField(help_text='حجم واقعی فایل بر حسب بایت', verbose_name='حجم فایل (Byte)')),
                ('checksum', models.CharField(help_text='هش فایل برای بررسی سلامت فایل', max_length=64, unique=True, verbose_name='SHA-256')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نسخه پشتیبان',
                'verbose_name_plural': 'نسخه\u200cهای پشتیبان',
                'ordering': ('-created_at',),
            },
        ),
    ]
