# Generated by Django 6.0.7 on 2026-07-24 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کاتالوگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('pdf_file', models.FileField(upload_to='catalog/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='فایل PDF')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'کاتالوگ شرکت',
                'verbose_name_plural': 'کاتالوگ شرکت',
            },
        ),
    ]
