# Generated by Django 6.0.7 on 2026-09-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycatalog',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='companycatalog',
            name='title_fa',
            field=models.CharField(default=1, max_length=200, verbose_name='عنوان کاتالوگ'),
            preserve_default=False,
        ),
    ]
