# Generated by Django 6.0.7 on 2026-09-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0002_rename_title_companycatalog_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycatalog',
            name='title_en',
            field=models.CharField(max_length=200, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AlterField(
            model_name='companycatalog',
            name='title_fa',
            field=models.CharField(max_length=200, verbose_name='عنوان فارسی'),
        ),
    ]
