# Generated by Django 6.0.7 on 2026-09-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0003_alter_companycatalog_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycatalog',
            old_name='description',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='companycatalog',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
