# Generated by Django 6.0.7 on 2026-09-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0004_rename_description_companycatalog_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycatalog',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='توضیحات انگلیسی'),
        ),
        migrations.AlterField(
            model_name='companycatalog',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات فارسی'),
        ),
    ]
