# Generated by Django 6.0.7 on 2026-07-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('summary_fa', models.TextField(verbose_name='متن قسمت اول فارسی')),
                ('summary_en', models.TextField(verbose_name='متن قسمت اول انگلیسی')),
                ('image', models.ImageField(default='news/default.jpg', upload_to='news/cover/', verbose_name='کاور خبر')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_special', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'رسانه',
                'verbose_name_plural': 'رسانه ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_media.media')),
            ],
            options={
                'verbose_name': 'تصویر رسانه',
                'verbose_name_plural': 'تصاویر رسانه',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='news/videos/')),
                ('duration', models.CharField(blank=True, max_length=10, null=True, verbose_name='مدت زمان ویدیو')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app_media.media')),
            ],
            options={
                'verbose_name': 'ویدیوی رسانه',
                'verbose_name_plural': 'ویدیوهای رسانه',
                'ordering': ['order', 'id'],
            },
        ),
    ]
