# Generated by Django 5.2.8 on 2026-02-05 16:42

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مناقصه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مناقصه',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TenderTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'برچسب مناقصه',
                'verbose_name_plural': 'برچسب\u200cهای مناقصه',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('tender_number', models.CharField(max_length=100, unique=True, verbose_name='شماره مناقصه')),
                ('start_date_fa', django_jalali.db.models.jDateField(help_text='1373-08-10', verbose_name='تاریخ شروع (شمسی)')),
                ('end_date_fa', django_jalali.db.models.jDateField(help_text='1373-08-10', verbose_name='تاریخ پایان (شمسی)')),
                ('start_date_en', models.DateField(verbose_name='تاریخ شروع (میلادی)')),
                ('end_date_en', models.DateField(verbose_name='تاریخ پایان (میلادی)')),
                ('poster', models.ImageField(upload_to='tender/posters', verbose_name='تصویر')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='tender/upload_file', verbose_name='آپلود فایل')),
                ('estimated_amount', models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ ضمانت مناقصه')),
                ('description_fa', models.TextField(verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(verbose_name='توضیحات انگلیسی')),
                ('status', models.CharField(choices=[('ongoing', 'در حال برگزاری'), ('extended', 'تمدید شده'), ('finished', 'پایان یافته')], default='ongoing', max_length=20, verbose_name='وضعیت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='app_tender.tendercategory', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(blank=True, related_name='tenders', to='app_tender.tendertag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'مناقصه',
                'verbose_name_plural': 'مناقصه\u200cها',
                'ordering': ['-created_at_fa'],
            },
        ),
        migrations.CreateModel(
            name='TenderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_fa', models.DateTimeField(auto_now_add=True)),
                ('updated_at_fa', models.DateTimeField(auto_now=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_en', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='tender/gallery', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح عکس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app_tender.tender', verbose_name='مناقصه')),
            ],
            options={
                'verbose_name': 'عکس گالری',
                'verbose_name_plural': 'گالری',
                'ordering': ('order',),
            },
        ),
    ]
