# Generated by Django 6.0.7 on 2026-07-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, help_text='آدرس IP بازدیدکننده', verbose_name='IP')),
                ('path', models.CharField(blank=True, db_index=True, default='', help_text='مسیر درخواستی', max_length=255, verbose_name='Page')),
                ('method', models.CharField(blank=True, default='GET', help_text='متود درخواست HTTP', max_length=10, verbose_name='HTTP Method')),
                ('user_agent', models.CharField(blank=True, default='', help_text='مرورگر و دستگاه کاربر', max_length=500, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, default='', help_text='صفحه مبدا', max_length=500, verbose_name='Referer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='First Visit')),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Activity')),
                ('visit_count', models.PositiveIntegerField(default=1, help_text='تعداد بازدیدهای این IP از همان مسیر', verbose_name='Visit Count')),
                ('is_bot', models.BooleanField(db_index=True, default=False, help_text='آیا این بازدید توسط ربات است؟', verbose_name='Is Bot')),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'بازدیدها',
                'ordering': ('-last_seen',),
                'indexes': [models.Index(fields=['ip', 'created_at'], name='app_visit_v_ip_cdf2d4_idx'), models.Index(fields=['path', 'created_at'], name='app_visit_v_path_9df786_idx'), models.Index(fields=['is_bot', 'created_at'], name='app_visit_v_is_bot_fd3e17_idx')],
            },
        ),
    ]
