# Generated by Django 6.0.7 on 2026-07-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-created_at'], 'verbose_name': 'بازدید', 'verbose_name_plural': 'بازدیدها'},
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='visit_created_idx',
            old_name='app_visit_v_created_71c0a2_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='visit_ip_idx',
            old_name='app_visit_v_ip_371bf5_idx',
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان بازدید'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, help_text='آیپی بازدیدکننده'),
        ),
    ]
