# Generated by Django 6.0.7 on 2026-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='browser',
            field=models.CharField(choices=[('chrome', 'کروم'), ('firefox', 'فایرفاکس'), ('safari', 'سافاری'), ('edge', 'اج'), ('opera', 'اپرا'), ('ie', 'اینترنت اکسپلورر'), ('other', 'سایر'), ('unknown', 'نامشخص')], db_index=True, default='unknown', max_length=20, verbose_name='مرورگر'),
        ),
        migrations.AddField(
            model_name='visit',
            name='device_model',
            field=models.CharField(blank=True, default='', help_text='مثلاً iPhone 14, Samsung Galaxy S23', max_length=100, verbose_name='مدل دستگاه'),
        ),
        migrations.AddField(
            model_name='visit',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'دسکتاپ'), ('mobile', 'موبایل'), ('tablet', 'تبلت'), ('bot', 'ربات'), ('unknown', 'نامشخص')], db_index=True, default='unknown', max_length=20, verbose_name='نوع دستگاه'),
        ),
        migrations.AddField(
            model_name='visit',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='زبان'),
        ),
        migrations.AddField(
            model_name='visit',
            name='os',
            field=models.CharField(choices=[('windows', 'ویندوز'), ('mac', 'مک'), ('linux', 'لینوکس'), ('android', 'اندروید'), ('ios', 'iOS'), ('other', 'سایر'), ('unknown', 'نامشخص')], db_index=True, default='unknown', max_length=20, verbose_name='سیستم\u200cعامل'),
        ),
        migrations.AddField(
            model_name='visit',
            name='screen_resolution',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='رزولوشن صفحه'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['device_type', 'created_at'], name='app_visit_v_device__5c765b_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['os', 'created_at'], name='app_visit_v_os_359e68_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['browser', 'created_at'], name='app_visit_v_browser_40322f_idx'),
        ),
    ]
