# Generated by Django 6.0.7 on 2026-07-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Bot'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='method',
            field=models.CharField(blank=True, default='GET', max_length=10, verbose_name='HTTP Method'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='referer',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Referer'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Visit Count'),
        ),
    ]
