# Generated by Django 6.0.7 on 2026-07-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_visit', '0002_alter_visit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('-created_at',), 'verbose_name': 'بازدید', 'verbose_name_plural': 'بازدیدها'},
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visit_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visit_ip_idx',
        ),
        migrations.AddField(
            model_name='visit',
            name='path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Page'),
        ),
        migrations.AddField(
            model_name='visit',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Visit Time'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, verbose_name='IP'),
        ),
    ]
