# Generated by Django 6.0.7 on 2026-07-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_visit', '0002_alter_visit_is_bot_alter_visit_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='اولین بازدید'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ربات'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین فعالیت'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='method',
            field=models.CharField(blank=True, default='GET', max_length=10, verbose_name='متد'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='مسیر صفحه'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='referer',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='ارجاع\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='مرورگر'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد بازدید'),
        ),
    ]
