# Generated by Django 6.0.7 on 2026-07-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_visit', '0003_alter_visit_options_remove_visit_visit_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('-last_seen',), 'verbose_name': 'بازدید', 'verbose_name_plural': 'بازدیدها'},
        ),
        migrations.AddField(
            model_name='visit',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Activity'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='First Visit'),
        ),
    ]
