# Generated by Django 6.0.7 on 2026-07-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_visit', '0004_alter_visit_options_visit_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('-last_seen',), 'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
        migrations.AddField(
            model_name='visit',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False, help_text='آیا این بازدید توسط ربات است؟', verbose_name='Is Bot'),
        ),
        migrations.AddField(
            model_name='visit',
            name='method',
            field=models.CharField(blank=True, default='GET', help_text='متود درخواست HTTP', max_length=10, verbose_name='HTTP Method'),
        ),
        migrations.AddField(
            model_name='visit',
            name='referer',
            field=models.URLField(blank=True, default='', help_text='صفحه مبدا', max_length=500, verbose_name='Referer'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_count',
            field=models.PositiveIntegerField(default=1, help_text='تعداد بازدیدهای این IP از همان مسیر', verbose_name='Visit Count'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, help_text='آدرس IP بازدیدکننده', verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='path',
            field=models.CharField(blank=True, db_index=True, default='', help_text='مسیر درخواستی', max_length=255, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user_agent',
            field=models.CharField(blank=True, default='', help_text='مرورگر و دستگاه کاربر', max_length=500, verbose_name='User Agent'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['ip', 'created_at'], name='app_visit_v_ip_cdf2d4_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['path', 'created_at'], name='app_visit_v_path_9df786_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['is_bot', 'created_at'], name='app_visit_v_is_bot_fd3e17_idx'),
        ),
    ]
