"""
Django settings for original_website project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gs9k^w59&yy8$%+^g8q=%0d@3fhsn3=y6u&p_p^k$=o3&ir(2$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'multi.captcha_admin',
    "jazzmin",
    'adminsortable2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_jalali',
    'django.contrib.humanize',

    'app_core.apps.AppBaseConfig',
    'app_banner.apps.AppBannerConfig',
    'app_blog.apps.AppBlogConfig',
    'app_news.apps.AppNewsConfig',
    'app_chart.apps.AppChartConfig',
    'app_product.apps.AppProductConfig',
    'app_tender.apps.AppTenderConfig',
    'app_tender_holding.apps.AppTenderHoldingConfig',
    'app_inquiry.apps.AppInquiryConfig',

    'app_auction.apps.AppAuctionConfig',
    'app_security.apps.AppSecurityConfig',
    'app_contact.apps.AppContactConfig',
    'app_reports.apps.AppReportsConfig',
    'app_hr.apps.AppHrConfig',
    'app_media.apps.AppMediaConfig',
    'app_sale.apps.AppSaleConfig',
    'app_catalog.apps.AppCatalogConfig',

    'django.contrib.sites',
    'django.contrib.sitemaps',
]
SITE_ID = 2
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'original_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'original_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [
    BASE_DIR / 'statics',
]
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


JAZZMIN_SETTINGS = {

    # ================================
    # 1) لوگو، عنوان و برندینگ اصلی
    # ================================
    "site_title": "پنل مدیریت",
    "site_header": "سیستم مدیریت مرکزی داروپخش",
    "site_brand": "داشبورد مدیریت",
    "welcome_sign": "به پنل مدیریت شرکت داروپخش خوش آمدید",
    "copyright":
        "© 2025 | تمامی حقوق برای شرکت کارخانجات داروپخش محفوظ است.",

    # ================================
    # 2) لوگو
    # ================================
    "site_logo": "admin-custom/images/logo.png",
    "login_logo": "admin-custom/images/logo.png",

    # ================================
    # 3) لینک‌های بالای صفحه (سایدبار بالا)
    # ================================
    "topmenu_links": [
        {
            "name": "👁️ مشاهده سایت",
            "url": "/",
            "new_window": True,
        },
    ],

    # ================================
    # 4) فایل‌های سفارشی
    # ================================
    "custom_css": "admin-custom/css/admin-custom.css",

}




DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
