"""
Django settings for original_website project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gs9k^w59&yy8$%+^g8q=%0d@3fhsn3=y6u&p_p^k$=o3&ir(2$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "jazzmin",

    'adminsortable2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_jalali',
    'django.contrib.humanize',
    'app_core.apps.AppBaseConfig',
    'app_banner.apps.AppBannerConfig',
    'app_blog.apps.AppBlogConfig',
    'app_news.apps.AppNewsConfig',
    'app_chart.apps.AppChartConfig',
    'app_product.apps.AppProductConfig',
    'app_tender.apps.AppTenderConfig',
    'app_tender_holding.apps.AppTenderHoldingConfig',
    'app_inquiry.apps.AppInquiryConfig',

    'app_admin',
    'app_auction.apps.AppAuctionConfig',
    'app_security.apps.AppSecurityConfig',
    'app_contact.apps.AppContactConfig',
    'app_reports.apps.AppReportsConfig',
    'app_hr.apps.AppHrConfig',
    'app_media.apps.AppMediaConfig',
    'app_sale.apps.AppSaleConfig',
    'app_catalog.apps.AppCatalogConfig',
    'app_visit.apps.AppVisitConfig',
    'app_resume.apps.AppResumeConfig',
    'app_log.apps.AppLogConfig',
    'app_seo.apps.AppSeoConfig',

    'django.contrib.sites',
    'django.contrib.sitemaps',
]
SITE_ID = 2
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # 👇 این را اضافه کن
    'app_log.middleware.CurrentRequestMiddleware',
    'app_seo.middleware.SEOMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'original_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "app_seo.context_processors.seo",
                "app_core.context_processors.common_context",
            ],
        },
    },
]

WSGI_APPLICATION = 'original_website.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fa'
LANGUAGES = [
    ("fa", "فارسی"),
]

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [
    BASE_DIR / 'statics',
]
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

from django.urls import reverse_lazy

from django.urls import reverse_lazy

# ═══════════════════════════════════════════════════════════
# 1. تنظیمات اصلی JAZZMIN
# ═══════════════════════════════════════════════════════════

JAZZMIN_SETTINGS = {

    # ═══ برندینگ ═══
    "site_title": "پنل مدیریت پیشرفته",
    "site_header": "پنل مدیریت",
    "site_brand": " داشبورد مدیریت",
    "welcome_sign": "👋",
    "copyright": "RJ ۱۴۰۵ - تمامی حقوق محفوظ است",

    "site_logo": "admin-custom/images/logos/logo.png",
    "login_logo": "admin-custom/images/logos/logo.png",
    "login_logo_dark": "admin-custom/images/logos/logo.png",
    "site_icon": "admin-custom/images/logos/favicon.ico",

    # ═══ منوی بالای هدر ═══
    "topmenu_links": [
        {"name": "🏠 مشاهده سایت", "url": "/", "new_window": True},
        # محصولات
        {"app": "app_product", "label": "🛍️ محصولات"},
        # وبلاگ
        {"app": "app_blog", "label": "📝 وبلاگ"},
        # اخبار
        {"app": "app_news", "label": "📰 اخبار"},
        # رسانه
        {"app": "app_media", "label": "🖼️ رسانه"},
        # کاتالوگ
        {"app": "app_catalog", "label": "📚 کاتالوگ"},

        # بنرها
        {"app": "app_banner", "label": "🖼️ بنرها"},
        # گزارشات
        {"app": "app_reports", "label": "📊 گزارشات"},
        {"app": "app_resume", "label": "📁 رزومه"},
        {"app": "app_log", "label": "📜 لاگ سیستم"},

    ],

    # ═══ منوی کاربری (گوشه بالا) ═══

    # ═══ سایدبار ═══
    "show_sidebar": True,
    "navigation_expanded": False,  # برای باز بودن همه منوها True کنید
    "hide_apps": [],  # اپ‌هایی که نمی‌خواهید نمایش داده شوند
    "hide_models": [],  # مدل‌هایی که نمی‌خواهید نمایش داده شوند

    # ═══ ترتیب نمایش (ساختار گروه‌بندی شده) ═══
    "order_with_respect_to": [
        # ─── ۱. مدیریت کاربران ───
        "auth",
        "auth.User",
        "auth.Group",

        # ─── ۲. فروش و محصولات ───
        "app_product",
        "app_product.Product",
        "app_product.ProductCategory",
        "app_product.ProductCategory2",
        "app_product.ProductTag",

        # ─── ۳. محتوا و رسانه ───
        "app_blog",
        "app_blog.blog",
        "app_blog.blog_Category",
        "app_blog.blog_Tag",
        "app_news",
        "app_news.News",
        "app_news.NewsCategory",
        "app_news.NewsTag",
        "app_media",
        "app_media.Media",

        # ─── ۴. مناقصات و مزایدات ───
        "app_tender",
        "app_tender.Tender",
        "app_tender.TenderCategory",
        "app_tender_holding",
        "app_tender_holding.Holding",
        "app_auction",
        "app_auction.Auction",

        # ─── ۵. استعلام و فروش ───
        "app_inquiry",
        "app_inquiry.PurchaseInquiry",
        "app_sale",
        "app_sale.SalesReport",

        # ─── ۶. کاتالوگ و چارت ───
        "app_catalog",
        "app_catalog.CompanyCatalog",
        "app_chart",
        "app_chart.Person",
        "app_chart.BoardMember",

        # ─── ۷. منابع انسانی ───
        "app_hr",
        "app_hr.JobOpportunity",
        "app_hr.JobApplication",

        # ─── ۸. ارتباطات ───
        "app_contact",
        "app_contact.ContactMessage",
        "app_security",
        "app_security.SecurityContact",

        # ─── ۹. تنظیمات و بنرها ───
        "app_banner",
        "app_banner.HeroSliderSetting",
        "app_banner.HeroBanner",
        "app_banner.MainBanner",
        "app_banner.OtherBanner",
        "app_banner.SpecialProductBanner",

        # ─── ۱۰. گزارشات ───
        "app_reports",
        "app_reports.SiteMainInfo",
        "app_reports.CorporateSection",
        "app_reports.CorporateStatistic",
        "app_reports.GroupCompany",
        "app_reports.DepartmentContact",
        "app_reports.FollowUsLink",

        # ─── ۱۱. آمار بازدیدها ───
        "app_visit",
        "app_visit.Visit",

        "app_resume",
        "app_resume.Resume",
        "app_resume.ResumeProvince",

        "app_log",
        "app_log.SystemLog",
    ],

    # ═══ آیکون‌های Font Awesome ───
    "icons": {

        # کاربران
        "auth": "fas fa-users",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-user-friends",

        # محصولات
        "app_product": "",
        "app_product.Product": "fas fa-box-open",
        "app_product.ProductCategory": "fas fa-folder",
        "app_product.ProductCategory2": "fas fa-folder-open",
        "app_product.ProductTag": "fas fa-tags",

        # وبلاگ
        "app_blog": "",
        "app_blog.blog": "fas fa-edit",
        "app_blog.blog_Category": "fas fa-folder",
        "app_blog.blog_Tag": "fas fa-tag",

        # اخبار
        "app_news": "",
        "app_news.News": "fas fa-bullhorn",
        "app_news.NewsCategory": "fas fa-folder",
        "app_news.NewsTag": "fas fa-tag",

        # رسانه
        "app_media": "",
        "app_media.Media": "fas fa-image",

        # مناقصه
        "app_tender": "",
        "app_tender.Tender": "fas fa-file-alt",
        "app_tender.TenderCategory": "fas fa-folder",

        "app_tender_holding": "",
        "app_tender_holding.Holding": "fas fa-industry",

        # مزایده
        "app_auction": "",
        "app_auction.Auction": "fas fa-gavel",

        # استعلام
        "app_inquiry": "",
        "app_inquiry.PurchaseInquiry": "fas fa-file-invoice",

        # فروش
        "app_sale": "",
        "app_sale.SalesReport": "fas fa-chart-line",

        # کاتالوگ
        "app_catalog": "",
        "app_catalog.CompanyCatalog": "fas fa-book-open",

        # چارت سازمانی
        "app_chart": "",
        "app_chart.Person": "fas fa-user-tie",
        "app_chart.BoardMember": "fas fa-user-shield",

        # منابع انسانی
        "app_hr": "",
        "app_hr.JobOpportunity": "fas fa-briefcase",
        "app_hr.JobApplication": "fas fa-file-signature",

        # ارتباط با ما
        "app_contact": "",
        "app_contact.ContactMessage": "fas fa-comments",

        # امنیت
        "app_security": "",
        "app_security.SecurityContact": "fas fa-lock",

        # بنر
        "app_banner": "",
        "app_banner.HeroBanner": "fas fa-desktop",
        "app_banner.OtherBanner": "fas fa-image",
        "app_banner.MainBanner": "fas fa-flag",
        "app_banner.SpecialProductBanner": "fas fa-star",
        "app_banner.HeroSliderSetting": "fas fa-sliders-h",

        # گزارشات
        "app_reports": "",
        "app_reports.SiteMainInfo": "fas fa-info-circle",
        "app_reports.FollowUsLink": "fas fa-link",
        "app_reports.CorporateStatistic": "fas fa-chart-pie",
        "app_reports.CorporateSection": "fas fa-layer-group",
        "app_reports.GroupCompany": "fas fa-city",
        "app_reports.DepartmentContact": "fas fa-phone",

        # آمار بازدیدها
        "app_visit": "",  # آیکون برای اپ
        "app_visit.Visit": "fas fa-eye",  # آیکون برای مدل Visit
        # رزومه
        "app_resume": "",
        "app_resume.Resume": "fas fa-file-alt",
        "app_resume.ResumeProvince": "fas fa-map-marker-alt",
        # لاگ سیستم
        "app_log": "",
        "app_log.SystemLog": "fas fa-history",
        "app_seo": "",
        "app_seo.SEOSetting": "fas fa-globe",
    },

    # آیکون‌های پیش‌فرض
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",

    # ═══ تنظیمات UI ═══
    "related_modal_active": True,  # نمایش مدال برای روابط
    "custom_css": "admin-custom/css/admin-custom.css",
    "use_google_fonts_cdn": False,
    "show_ui_builder": False,

    # فرم تغییر
    "changeform_format": "horizontal_tabs",  # یا "vertical_tabs" یا "collapsible"
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "collapsible",
    },

    # زبان
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {

    # ═══ تم‌ها ═══
    "theme": "flatly",  # تم اصلی (نور)
    "dark_mode_theme": "darkly",  # تم دارک (خودکار)

    # ═══ رنگ‌بندی برند ═══
    "brand_colour": "navbar-primary",  # یا "navbar-info", "navbar-success"
    "accent": "accent-primary",  # رنگ تاکیدی
    "navbar": "navbar-dark",  # نوار بالا (dark/light)
    "sidebar": "sidebar-dark-primary",  # سایدبار

    # ═══ اندازه فونت‌ها ═══
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "sidebar_nav_small_text": False,

    # ═══ نوار بالا ═══
    "navbar_fixed": True,  # ثابت در بالا
    "no_navbar_border": True,  # بدون حاشیه

    # ═══ سایدبار ═══
    "sidebar_fixed": True,  # ثابت
    "sidebar_nav_child_indent": True,  # تورفتگی زیرمنوها
    "sidebar_nav_compact_style": True,  # استایل فشرده
    "sidebar_nav_legacy_style": False,  # غیرفعال کردن استایل قدیمی
    "sidebar_nav_flat_style": True,  # استایل تخت و مدرن
    "sidebar_disable_expand": False,  # قابلیت باز/بسته شدن

    # ═══ فوتر ═══
    "footer_fixed": False,

    # ═══ چیدمان صفحه ═══
    "layout_boxed": False,  # صفحه تمام‌عرض

    # ═══ دکمه‌ها ═══
    # "button_classes": {
    #     "primary": "btn-primary",  # دکمه‌های کامل با رنگ
    #     "secondary": "btn-secondary",
    #     "info": "btn-info",
    #     "warning": "btn-warning",
    #     "danger": "btn-danger",
    #     "success": "btn-success",
    # },
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },

    # ═══ ویژگی‌های اضافی ═══
    "actions_sticky_top": True,  # دکمه‌های عملیاتی چسبنده
}

# ═══════════════════════════════════════════════════════════
# 3. تنظیمات اختیاری برای جستجو و فیلتر
# ═══════════════════════════════════════════════════════════

JAZZMIN_SETTINGS["global_search"] = [
    "app_product.Product",
    "app_blog.blog",
    "app_news.News",
    "auth.User",
]
