# Generated by Django 6.0.7 on 2026-07-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('page', '📄 صفحه ثابت'), ('product', '📦 محصول'), ('blog', '📝 مقاله'), ('news', '📰 خبر'), ('media', '🎥 رسانه'), ('tender', '📑 مناقصه'), ('holding', '🏢 شرکت هلدینگ'), ('auction', '🏛 مزایده'), ('catalog', '📚 کاتالوگ'), ('resume', '💼 رزومه'), ('hr', '👨\u200d💼 فرصت شغلی'), ('chart', '📊 چارت سازمانی'), ('other', '🔹 سایر')], default='page', help_text='مشخص کنید این تنظیمات SEO برای چه نوع محتوایی است.', max_length=30, verbose_name='نوع محتوا')),
                ('page_key', models.CharField(blank=True, help_text='برای صفحات ثابت مانند درباره ما، تماس با ما و... یک شناسه یکتا وارد کنید.', max_length=100, null=True, verbose_name='کلید صفحه')),
                ('app_label', models.CharField(blank=True, help_text='نام اپلیکیشن Django مربوط به محتوا (مثلاً app_product).', max_length=100, null=True, verbose_name='نام اپلیکیشن')),
                ('model_name', models.CharField(blank=True, help_text='نام مدل Django مربوط به محتوا (مثلاً Product).', max_length=100, null=True, verbose_name='نام مدل')),
                ('object_id', models.PositiveBigIntegerField(blank=True, help_text='شناسه رکورد مربوط به محصول، مقاله، خبر یا سایر محتواها.', null=True, verbose_name='شناسه محتوا')),
                ('url', models.URLField(blank=True, help_text='در صورت نیاز آدرس کامل صفحه را وارد کنید.', null=True, verbose_name='آدرس صفحه')),
                ('title', models.CharField(help_text='عنوانی که در نتایج گوگل نمایش داده می\u200cشود. بهتر است کمتر از 70 کاراکتر باشد.', max_length=70, verbose_name='عنوان SEO')),
                ('description', models.CharField(help_text='توضیح کوتاه صفحه برای نمایش در موتورهای جستجو. بهتر است حدود 160 کاراکتر باشد.', max_length=160, verbose_name='توضیحات SEO')),
                ('keywords', models.TextField(blank=True, help_text='کلمات مرتبط با محتوا را با کاما جدا کنید.', verbose_name='کلمات کلیدی')),
                ('canonical', models.URLField(blank=True, help_text='آدرس اصلی صفحه برای جلوگیری از محتوای تکراری.', verbose_name='Canonical')),
                ('robots', models.CharField(default='index,follow', help_text='قوانین ایندکس شدن صفحه توسط موتورهای جستجو.', max_length=100, verbose_name='Robots')),
                ('og_title', models.CharField(blank=True, help_text='عنوانی که هنگام اشتراک لینک در شبکه\u200cهای اجتماعی نمایش داده می\u200cشود.', max_length=70, verbose_name='عنوان شبکه اجتماعی')),
                ('og_description', models.CharField(blank=True, help_text='توضیح نمایش داده شده هنگام اشتراک لینک در شبکه\u200cهای اجتماعی.', max_length=160, verbose_name='توضیحات شبکه اجتماعی')),
                ('og_image', models.ImageField(blank=True, help_text='تصویری که هنگام اشتراک صفحه در شبکه\u200cهای اجتماعی نمایش داده می\u200cشود.', null=True, upload_to='seo/og/', verbose_name='تصویر شبکه اجتماعی')),
                ('og_type', models.CharField(default='website', help_text='نوع محتوا برای شبکه\u200cهای اجتماعی مانند website، article و...', max_length=30, verbose_name='نوع Open Graph')),
                ('schema_json', models.JSONField(blank=True, help_text='اطلاعات ساختاریافته برای گوگل مانند محصول، مقاله، سازمان و...', null=True, verbose_name='Schema JSON-LD')),
                ('is_active', models.BooleanField(default=True, help_text='در صورت فعال بودن این تنظیمات SEO روی سایت اعمال می\u200cشود.', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': '⚙️ تنظیم SEO',
                'verbose_name_plural': '⚙️ تنظیمات SEO',
                'indexes': [models.Index(fields=['content_type', 'page_key'], name='app_seo_seo_content_ef85c9_idx'), models.Index(fields=['app_label', 'model_name', 'object_id'], name='app_seo_seo_app_lab_1c4b3c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('object_id__isnull', False)), fields=('app_label', 'model_name', 'object_id'), name='unique_seo_object'), models.UniqueConstraint(condition=models.Q(('content_type', 'page')), fields=('page_key',), name='unique_seo_page')],
            },
        ),
    ]
