# Generated by Django 6.0.7 on 2026-07-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('page', '📄 صفحه ثابت'), ('product', '📦 محصول'), ('blog', '📝 مقاله'), ('news', '📰 خبر'), ('media', '🎥 رسانه'), ('tender', '📑 مناقصه'), ('holding', '🏢 شرکت هلدینگ'), ('auction', '🏛 مزایده'), ('catalog', '📚 کاتالوگ'), ('resume', '💼 رزومه'), ('hr', '👨\u200d💼 فرصت شغلی'), ('chart', '📊 چارت سازمانی'), ('other', '🔹 سایر')], default='page', max_length=30, verbose_name='نوع محتوا')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='اپلیکیشن')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شناسه محتوا')),
                ('page_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='کلید صفحه')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس صفحه')),
                ('title', models.CharField(max_length=70, verbose_name='عنوان SEO')),
                ('description', models.CharField(max_length=160, verbose_name='توضیحات SEO')),
                ('keywords', models.TextField(blank=True, verbose_name='کلمات کلیدی')),
                ('canonical', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('robots', models.CharField(default='index,follow', max_length=100, verbose_name='Robots')),
                ('og_title', models.CharField(blank=True, max_length=70, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='تصویر شبکه اجتماعی')),
                ('og_type', models.CharField(default='website', max_length=30, verbose_name='OG Type')),
                ('twitter_title', models.CharField(blank=True, max_length=70, verbose_name='Twitter Title')),
                ('twitter_description', models.CharField(blank=True, max_length=160, verbose_name='Twitter Description')),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='seo/twitter/', verbose_name='Twitter Image')),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=50, verbose_name='Twitter Card')),
                ('schema_json', models.JSONField(blank=True, null=True, verbose_name='Schema JSON-LD')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': '⚙️ تنظیم SEO',
                'verbose_name_plural': '⚙️ تنظیمات SEO',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='app_seo_seo_content_d26ee5_idx'), models.Index(fields=['app_label', 'model_name'], name='app_seo_seo_app_lab_d7b215_idx')],
            },
        ),
    ]
