# Generated by Django 6.0.7 on 2026-07-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seosetting',
            name='twitter_card',
        ),
        migrations.RemoveField(
            model_name='seosetting',
            name='twitter_description',
        ),
        migrations.RemoveField(
            model_name='seosetting',
            name='twitter_image',
        ),
        migrations.RemoveField(
            model_name='seosetting',
            name='twitter_title',
        ),
    ]
