# Generated by Django 6.0.7 on 2026-10-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='امتیاز')),
                ('checks', models.JSONField(blank=True, default=dict, verbose_name='جزئیات بررسی\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تحلیل')),
            ],
            options={
                'verbose_name': '📊 لاگ تحلیل SEO',
                'verbose_name_plural': '📊 لاگ\u200cهای تحلیل SEO',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SEODefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English')], default='fa', max_length=5, verbose_name='زبان')),
                ('content_type', models.CharField(choices=[('page', '📄 صفحه ثابت'), ('product', '📦 محصول'), ('blog', '📝 مقاله'), ('news', '📰 خبر'), ('media', '🎥 رسانه'), ('tender', '📑 مناقصه'), ('holding', '🏢 شرکت هلدینگ'), ('auction', '🏛 مزایده'), ('catalog', '📚 کاتالوگ'), ('resume', '💼 رزومه'), ('hr', '👨\u200d💼 فرصت شغلی'), ('chart', '📊 چارت سازمانی'), ('other', '🔹 سایر')], max_length=30, verbose_name='نوع محتوا')),
                ('title_template', models.CharField(blank=True, help_text='می\u200cتوانید از {title} و {site} استفاده کنید.', max_length=150, verbose_name='الگوی عنوان')),
                ('description_template', models.CharField(blank=True, help_text='می\u200cتوانید از {title} و {site} استفاده کنید.', max_length=250, verbose_name='الگوی توضیحات')),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='seo/defaults/', verbose_name='تصویر پیش\u200cفرض OG')),
                ('default_schema_type', models.CharField(choices=[('auto', '🤖 خودکار'), ('Organization', 'Organization'), ('WebSite', 'WebSite'), ('WebPage', 'WebPage'), ('AboutPage', 'AboutPage'), ('ContactPage', 'ContactPage'), ('Product', 'Product'), ('Article', 'Article'), ('NewsArticle', 'NewsArticle'), ('BreadcrumbList', 'BreadcrumbList'), ('FAQPage', 'FAQPage'), ('Person', 'Person'), ('CreativeWork', 'CreativeWork'), ('CollectionPage', 'CollectionPage')], default='auto', max_length=40, verbose_name='نوع Schema پیش\u200cفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': '🧩 پیش\u200cفرض SEO',
                'verbose_name_plural': '🧩 پیش\u200cفرض\u200cهای SEO',
            },
        ),
        migrations.AddField(
            model_name='seosetting',
            name='breadcrumb_title',
            field=models.CharField(blank=True, help_text='در صورت خالی بودن، از عنوان SEO استفاده می\u200cشود.', max_length=120, verbose_name='عنوان Breadcrumb'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='focus_keyphrase',
            field=models.CharField(blank=True, help_text='عبارتی که می\u200cخواهید این صفحه برای آن رتبه بگیرد (Yoast Focus Keyphrase).', max_length=120, verbose_name='عبارت کلیدی اصلی'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='follow_control',
            field=models.CharField(choices=[('follow', 'Follow'), ('nofollow', 'No Follow')], default='follow', max_length=10, verbose_name='Follow'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='hreflang_group',
            field=models.CharField(blank=True, help_text='شناسه مشترک برای صفحات زبان\u200cهای مختلف یک محتوا.', max_length=100, verbose_name='گروه Hreflang'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='index_control',
            field=models.CharField(choices=[('index', 'Index'), ('noindex', 'No Index')], default='index', max_length=10, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='publish_status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('scheduled', 'زمان\u200cبندی شده'), ('expired', 'منقضی شده')], default='published', max_length=20, verbose_name='وضعیت انتشار'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='schema_type',
            field=models.CharField(choices=[('auto', '🤖 خودکار'), ('Organization', 'Organization'), ('WebSite', 'WebSite'), ('WebPage', 'WebPage'), ('AboutPage', 'AboutPage'), ('ContactPage', 'ContactPage'), ('Product', 'Product'), ('Article', 'Article'), ('NewsArticle', 'NewsArticle'), ('BreadcrumbList', 'BreadcrumbList'), ('FAQPage', 'FAQPage'), ('Person', 'Person'), ('CreativeWork', 'CreativeWork'), ('CollectionPage', 'CollectionPage')], default='auto', help_text='در حالت خودکار، بر اساس نوع محتوا انتخاب می\u200cشود.', max_length=40, verbose_name='نوع Schema'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='seo_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='امتیاز ۰ تا ۱۰۰ که توسط تحلیل\u200cگر Yoast محاسبه می\u200cشود.', verbose_name='امتیاز SEO'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='twitter_card',
            field=models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', max_length=30, verbose_name='نوع Twitter Card'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='twitter_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='توضیحات توییتر'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='twitter_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/twitter/', verbose_name='تصویر توییتر'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='عنوان توییتر'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='robots',
            field=models.CharField(default='index,follow', help_text='مقدار کامل robots. برای کنترل دقیق\u200cتر از فیلدهای Index و Follow استفاده کنید.', max_length=100, verbose_name='Robots (سازگاری)'),
        ),
        migrations.AddIndex(
            model_name='seosetting',
            index=models.Index(fields=['focus_keyphrase'], name='app_seo_seo_focus_k_d2aae6_idx'),
        ),
        migrations.AddIndex(
            model_name='seosetting',
            index=models.Index(fields=['hreflang_group'], name='app_seo_seo_hreflan_b7b23d_idx'),
        ),
        migrations.AddField(
            model_name='seoanalysislog',
            name='seo_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_logs', to='app_seo.seosetting', verbose_name='تنظیم SEO'),
        ),
        migrations.AddConstraint(
            model_name='seodefault',
            constraint=models.UniqueConstraint(fields=('language', 'content_type'), name='unique_seo_default_per_language'),
        ),
    ]
