# Generated by Django 6.0.7 on 2026-07-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seo', '0002_alter_seosetting_app_label_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seosetting',
            name='app_seo_seo_page_ke_602d55_idx',
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='app_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اپلیکیشن'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='تصویر شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_type',
            field=models.CharField(default='website', max_length=30, verbose_name='OG Type'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
    ]
