# Generated by Django 6.0.7 on 2026-07-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seo', '0002_remove_seosetting_twitter_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='app_label',
            field=models.CharField(blank=True, help_text='نام اپلیکیشن Django مربوط به محتوا (مثلاً app_product).', max_length=100, null=True, verbose_name='نام اپلیکیشن'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='canonical',
            field=models.URLField(blank=True, help_text='آدرس اصلی صفحه برای جلوگیری از محتوای تکراری.', verbose_name='Canonical'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='content_type',
            field=models.CharField(choices=[('page', '📄 صفحه ثابت'), ('product', '📦 محصول'), ('blog', '📝 مقاله'), ('news', '📰 خبر'), ('media', '🎥 رسانه'), ('tender', '📑 مناقصه'), ('holding', '🏢 شرکت هلدینگ'), ('auction', '🏛 مزایده'), ('catalog', '📚 کاتالوگ'), ('resume', '💼 رزومه'), ('hr', '👨\u200d💼 فرصت شغلی'), ('chart', '📊 چارت سازمانی'), ('other', '🔹 سایر')], default='page', help_text='مشخص کنید این تنظیمات SEO برای چه نوع محتوایی است.', max_length=30, verbose_name='نوع محتوا'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='description',
            field=models.CharField(help_text='توضیح کوتاه صفحه برای نمایش در موتورهای جستجو. بهتر است حدود 160 کاراکتر باشد.', max_length=160, verbose_name='توضیحات SEO'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='در صورت فعال بودن این تنظیمات SEO روی سایت اعمال می\u200cشود.', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='keywords',
            field=models.TextField(blank=True, help_text='کلمات مرتبط با محتوا را با کاما جدا کنید.', verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='model_name',
            field=models.CharField(blank=True, help_text='نام مدل Django مربوط به محتوا (مثلاً Product).', max_length=100, null=True, verbose_name='نام مدل'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='شناسه رکورد مربوط به محصول، مقاله، خبر یا سایر محتواها.', null=True, verbose_name='شناسه محتوا'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_description',
            field=models.CharField(blank=True, help_text='توضیح نمایش داده شده هنگام اشتراک لینک در شبکه\u200cهای اجتماعی.', max_length=160, verbose_name='توضیحات شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_image',
            field=models.ImageField(blank=True, help_text='تصویری که هنگام اشتراک صفحه در شبکه\u200cهای اجتماعی نمایش داده می\u200cشود.', null=True, upload_to='seo/og/', verbose_name='تصویر شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_title',
            field=models.CharField(blank=True, help_text='عنوانی که هنگام اشتراک لینک در شبکه\u200cهای اجتماعی نمایش داده می\u200cشود.', max_length=70, verbose_name='عنوان شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_type',
            field=models.CharField(default='website', help_text='نوع محتوا برای شبکه\u200cهای اجتماعی مانند website، article و...', max_length=30, verbose_name='نوع Open Graph'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='page_key',
            field=models.CharField(blank=True, help_text='برای صفحات ثابت مانند درباره ما، تماس با ما و... یک شناسه یکتا وارد کنید.', max_length=100, null=True, verbose_name='کلید صفحه'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='robots',
            field=models.CharField(default='index,follow', help_text='قوانین ایندکس شدن صفحه توسط موتورهای جستجو.', max_length=100, verbose_name='Robots'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='schema_json',
            field=models.JSONField(blank=True, help_text='اطلاعات ساختاریافته برای گوگل مانند محصول، مقاله، سازمان و...', null=True, verbose_name='Schema JSON-LD'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='title',
            field=models.CharField(help_text='عنوانی که در نتایج گوگل نمایش داده می\u200cشود. بهتر است کمتر از 70 کاراکتر باشد.', max_length=70, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='url',
            field=models.URLField(blank=True, help_text='در صورت نیاز آدرس کامل صفحه را وارد کنید.', null=True, verbose_name='آدرس صفحه'),
        ),
    ]
