# Generated by Django 6.0.7 on 2026-07-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seo', '0003_remove_seosetting_app_seo_seo_page_ke_602d55_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='app_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام اپلیکیشن'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدل'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='توضیحات Open Graph'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='تصویر Open Graph'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='عنوان Open Graph'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_type',
            field=models.CharField(default='website', max_length=30, verbose_name='نوع Open Graph'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddIndex(
            model_name='seosetting',
            index=models.Index(fields=['page_key'], name='app_seo_seo_page_ke_602d55_idx'),
        ),
    ]
