# Generated by Django 6.0.7 on 2026-07-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seo', '0004_alter_seosetting_app_label_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seosetting',
            constraint=models.UniqueConstraint(fields=('content_type', 'page_key'), name='unique_page_seo'),
        ),
        migrations.AddConstraint(
            model_name='seosetting',
            constraint=models.UniqueConstraint(fields=('app_label', 'model_name', 'object_id'), name='unique_object_seo'),
        ),
    ]
