# Generated by Django 6.0.7 on 2026-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seo', '0005_seosetting_unique_page_seo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seosetting',
            name='unique_page_seo',
        ),
        migrations.RemoveConstraint(
            model_name='seosetting',
            name='unique_object_seo',
        ),
        migrations.RemoveIndex(
            model_name='seosetting',
            name='app_seo_seo_content_d26ee5_idx',
        ),
        migrations.RemoveIndex(
            model_name='seosetting',
            name='app_seo_seo_app_lab_d7b215_idx',
        ),
        migrations.RemoveIndex(
            model_name='seosetting',
            name='app_seo_seo_page_ke_602d55_idx',
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='canonical',
            field=models.URLField(blank=True, verbose_name='Canonical'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='OG Image'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='og_type',
            field=models.CharField(default='website', max_length=30, verbose_name='OG Type'),
        ),
        migrations.AddIndex(
            model_name='seosetting',
            index=models.Index(fields=['content_type', 'page_key'], name='app_seo_seo_content_ef85c9_idx'),
        ),
        migrations.AddIndex(
            model_name='seosetting',
            index=models.Index(fields=['app_label', 'model_name', 'object_id'], name='app_seo_seo_app_lab_1c4b3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='seosetting',
            constraint=models.UniqueConstraint(fields=('app_label', 'model_name', 'object_id'), name='unique_seo_object'),
        ),
    ]
