# Generated by Django 6.0.7 on 2026-07-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seo', '0006_remove_seosetting_unique_page_seo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seosetting',
            name='unique_seo_object',
        ),
        migrations.AddConstraint(
            model_name='seosetting',
            constraint=models.UniqueConstraint(condition=models.Q(('object_id__isnull', False)), fields=('app_label', 'model_name', 'object_id'), name='unique_seo_object'),
        ),
        migrations.AddConstraint(
            model_name='seosetting',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type', 'page')), fields=('page_key',), name='unique_seo_page'),
        ),
    ]
