# Generated by Django 6.0.7 on 2026-07-27 19:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name_fa', models.CharField(help_text='مثال: تهران، اصفهان، شیراز', max_length=100, verbose_name='نام استان یا شهر (فارسی)')),
                ('province_name_en', models.CharField(help_text='Example: Tehran, Isfahan, Shiraz', max_length=100, verbose_name='نام استان یا شهر (انگلیسی)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': ' شهر یا استان',
                'verbose_name_plural': ' شهرها و استان\u200cها',
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name_fa', models.CharField(max_length=200, verbose_name='نام پروژه (فارسی)')),
                ('project_name_en', models.CharField(max_length=200, verbose_name='نام پروژه (انگلیسی)')),
                ('svg_file', models.FileField(upload_to='resume/svg/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='فایل SVG')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to='app_resume.resumeprovince', verbose_name='استان / شهر')),
            ],
            options={
                'verbose_name': 'رزومه',
                'verbose_name_plural': 'رزومه\u200cها',
                'ordering': ('display_order',),
            },
        ),
    ]
