# Generated by Django 6.0.7 on 2026-07-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='resumeprovince',
            name='svg_file',
        ),
        migrations.AddField(
            model_name='resume',
            name='project_name_en',
            field=models.CharField(default=1, max_length=200, verbose_name='نام پروژه (انگلیسی)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='project_name_fa',
            field=models.CharField(default=1, max_length=200, verbose_name='نام پروژه (فارسی)'),
            preserve_default=False,
        ),
    ]
