# Generated by Django 6.0.7 on 2026-07-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_resume', '0002_remove_resume_project_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeprovince',
            options={'ordering': ('display_order',), 'verbose_name': ' شهر یا استان', 'verbose_name_plural': ' شهرها و استان\u200cها'},
        ),
    ]
