# Generated by Django 6.0.7 on 2026-07-24 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی')),
                ('cat_icon', models.FileField(blank=True, null=True, upload_to='products/category_icons/', verbose_name='آیکون (SVG)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('priority', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'شکل محصول',
                'verbose_name_plural': 'شکل محصول',
                'ordering': ['priority', 'title_fa'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('priority', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
                'ordering': ['priority', 'title_fa'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('priority', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'برچسب ',
                'verbose_name_plural': 'برچسب\u200cهای ',
                'ordering': ['priority', 'title_fa'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='نام محصول (فارسی)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='نام محصول-برند (انگلیسی)')),
                ('summary_fa', models.TextField(blank=True, verbose_name='توضیح کوتاه (فارسی)')),
                ('summary_en', models.TextField(blank=True, verbose_name='توضیح کوتاه (انگلیسی)')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('special', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/main/', verbose_name='تصویر اصلی')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='products/qr/', verbose_name='QR code')),
                ('qr_data', models.CharField(blank=True, max_length=255, verbose_name='QR data')),
                ('generic_name_fa', models.CharField(blank=True, max_length=255, verbose_name='مدل (فارسی)')),
                ('generic_name_en', models.CharField(blank=True, max_length=255, verbose_name='مدل (انگلیسی)')),
                ('description_1_fa', models.TextField(blank=True, verbose_name='مشخصات فنی (فارسی)')),
                ('description_1_en', models.TextField(blank=True, verbose_name='Description 1 (English)')),
                ('description_2_fa', models.TextField(blank=True, verbose_name='قابلیت ها (فارسی)')),
                ('description_2_en', models.TextField(blank=True, verbose_name='Description 2 (English)')),
                ('description_3_fa', models.TextField(blank=True, verbose_name='رنگ بندی های موجود')),
                ('description_3_en', models.TextField(blank=True, verbose_name='Description 3 (English)')),
                ('description_4_fa', models.TextField(blank=True, verbose_name='رنگ بندی های سفارشی (فارسی)')),
                ('description_4_en', models.TextField(blank=True, verbose_name='Description 4 (English)')),
                ('description_5_fa', models.TextField(blank=True, verbose_name='توضیحات ۵ (فارسی)')),
                ('description_5_en', models.TextField(blank=True, verbose_name='Description 5 (English)')),
                ('description_6_fa', models.TextField(blank=True, verbose_name='توضیحات ۶ (فارسی)')),
                ('description_6_en', models.TextField(blank=True, verbose_name='Description 6 (English)')),
                ('description_7_fa', models.TextField(blank=True, verbose_name='توضیحات ۷ (فارسی)')),
                ('description_7_en', models.TextField(blank=True, verbose_name='Description 7 (English)')),
                ('description_8_fa', models.TextField(blank=True, verbose_name='توضیحات ۸ (فارسی)')),
                ('description_8_en', models.TextField(blank=True, verbose_name='Description 8 (English)')),
                ('description_9_fa', models.TextField(blank=True, verbose_name='توضیحات ۹ (فارسی)')),
                ('description_9_en', models.TextField(blank=True, verbose_name='Description 9 (English)')),
                ('description_10_fa', models.TextField(blank=True, verbose_name='توضیحات ۱۰ (فارسی)')),
                ('description_10_en', models.TextField(blank=True, verbose_name='Description 10 (English)')),
                ('sku', models.CharField(max_length=128, verbose_name='کد محصول')),
                ('priority', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=170, verbose_name='Meta Description')),
                ('robots', models.CharField(default='index,follow', max_length=30, verbose_name='Robots')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app_product.productcategory', verbose_name='شکل محصول')),
                ('category2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products2', to='app_product.productcategory2', verbose_name='دسته بندی')),
                ('tags', models.ManyToManyField(blank=True, to='app_product.producttag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['priority', 'title_fa'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='نام رنگ')),
                ('color_code', models.CharField(help_text='مثال: #FF0000', max_length=7, verbose_name='کد رنگ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='app_product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'رنگ محصول',
                'verbose_name_plural': 'رنگ\u200cهای محصول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='عکس')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='آپلود')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'گالری محصولات',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User Agent')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان اسکن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='app_product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'اسکن محصول',
                'verbose_name_plural': 'اسکن محصولات',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
