# Generated by Django 6.0.6 on 2026-06-24 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی')),
                ('cat_icon', models.FileField(blank=True, null=True, upload_to='products/category_icons/', verbose_name='آیکون (SVG)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('priority', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'شکل دارویی',
                'verbose_name_plural': 'شکل دارویی',
                'ordering': ['priority', 'title_fa'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('priority', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته بندی دارویی',
                'verbose_name_plural': 'دسته بندی دارویی',
                'ordering': ['priority', 'title_fa'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('priority', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'برچسب دارویی',
                'verbose_name_plural': 'برچسب\u200cهای دارویی',
                'ordering': ['priority', 'title_fa'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='نام محصول (فارسی)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='نام محصول-برند (انگلیسی)')),
                ('summary_fa', models.TextField(blank=True, verbose_name='توضیح کوتاه (فارسی)')),
                ('summary_en', models.TextField(blank=True, verbose_name='توضیح کوتاه (انگلیسی)')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('special', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/main/', verbose_name='تصویر اصلی')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='products/qr/', verbose_name='QR code')),
                ('qr_data', models.CharField(blank=True, max_length=255, verbose_name='QR data')),
                ('generic_name_fa', models.CharField(blank=True, max_length=255, verbose_name='نام ژنریک (فارسی)')),
                ('generic_name_en', models.CharField(blank=True, max_length=255, verbose_name='نام ژنریک (انگلیسی)')),
                ('composition_fa', models.TextField(blank=True, verbose_name='ترکیبات (فارسی)')),
                ('composition_en', models.TextField(blank=True, verbose_name='ترکیبات (انگلیسی)')),
                ('indications_fa', models.TextField(blank=True, verbose_name='موارد مصرف (فارسی)')),
                ('indications_en', models.TextField(blank=True, verbose_name='موارد مصرف (انگلیسی)')),
                ('contra_fa', models.TextField(blank=True, verbose_name='موارد منع مصرف (فارسی)')),
                ('contra_en', models.TextField(blank=True, verbose_name='موارد منع مصرف (انگلیسی)')),
                ('warnings_fa', models.TextField(blank=True, verbose_name='هشدارها (فارسی)')),
                ('warnings_en', models.TextField(blank=True, verbose_name='هشدارها (انگلیسی)')),
                ('pregnancy_use_fa', models.TextField(blank=True, verbose_name='مصرف در بارداری (فارسی)')),
                ('pregnancy_use_en', models.TextField(blank=True, verbose_name='مصرف در بارداری (انگلیسی)')),
                ('instructions_fa', models.TextField(blank=True, verbose_name='نحوه مصرف (فارسی)')),
                ('instructions_en', models.TextField(blank=True, verbose_name='نحوه مصرف (انگلیسی)')),
                ('interactions_fa', models.TextField(blank=True, verbose_name='تداخلات (فارسی)')),
                ('interactions_en', models.TextField(blank=True, verbose_name='تداخلات (انگلیسی)')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات (فارسی)')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات (انگلیسی)')),
                ('sku', models.CharField(max_length=128, verbose_name='کد محصول')),
                ('priority', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app_product.productcategory', verbose_name='شکل دارویی')),
                ('category2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products2', to='app_product.productcategory2', verbose_name='دسته بندی دارویی')),
                ('tags', models.ManyToManyField(blank=True, to='app_product.producttag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['priority', 'title_fa'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='عکس')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='آپلود')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'گالری محصولات',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User Agent')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان اسکن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='app_product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'اسکن محصول',
                'verbose_name_plural': 'اسکن محصولات',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
