# Generated by Django 6.0.7 on 2026-07-12 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['priority', 'title_fa'], 'verbose_name': 'شکل محصول', 'verbose_name_plural': 'شکل محصول'},
        ),
        migrations.AlterModelOptions(
            name='productcategory2',
            options={'ordering': ['priority', 'title_fa'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'ordering': ['priority', 'title_fa'], 'verbose_name': 'برچسب ', 'verbose_name_plural': 'برچسب\u200cهای '},
        ),
        migrations.RemoveField(
            model_name='product',
            name='composition_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='composition_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='contra_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='contra_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='indications_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='indications_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='instructions_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='instructions_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='interactions_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='interactions_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pregnancy_use_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pregnancy_use_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warnings_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warnings_fa',
        ),
        migrations.AddField(
            model_name='product',
            name='description_10_en',
            field=models.TextField(blank=True, verbose_name='Description 10 (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_10_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات ۱۰ (فارسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_1_en',
            field=models.TextField(blank=True, verbose_name='Description 1 (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_1_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات ۱ (فارسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_2_en',
            field=models.TextField(blank=True, verbose_name='Description 2 (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_2_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات ۲ (فارسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_3_en',
            field=models.TextField(blank=True, verbose_name='Description 3 (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_3_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات ۳ (فارسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_4_en',
            field=models.TextField(blank=True, verbose_name='Description 4 (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_4_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات ۴ (فارسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_5_en',
            field=models.TextField(blank=True, verbose_name='Description 5 (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_5_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات ۵ (فارسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_6_en',
            field=models.TextField(blank=True, verbose_name='Description 6 (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_6_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات ۶ (فارسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_7_en',
            field=models.TextField(blank=True, verbose_name='Description 7 (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_7_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات ۷ (فارسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_8_en',
            field=models.TextField(blank=True, verbose_name='Description 8 (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_8_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات ۸ (فارسی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_9_en',
            field=models.TextField(blank=True, verbose_name='Description 9 (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_9_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات ۹ (فارسی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app_product.productcategory', verbose_name='شکل محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products2', to='app_product.productcategory2', verbose_name='دسته بندی'),
        ),
    ]
