# Generated by Django 6.0.7 on 2026-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_product_meta_description_product_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='generic_name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='مدل (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic_name_fa',
            field=models.CharField(blank=True, max_length=255, verbose_name='مدل (فارسی)'),
        ),
    ]
