# Generated by Django 6.0.7 on 2026-07-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_productcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_1_fa',
            field=models.TextField(blank=True, verbose_name='مشخصات فنی (فارسی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_2_fa',
            field=models.TextField(blank=True, verbose_name='قابلیت ها (فارسی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_3_fa',
            field=models.TextField(blank=True, verbose_name='رنگ بندی های موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_4_fa',
            field=models.TextField(blank=True, verbose_name='رنگ بندی های سفارشی (فارسی)'),
        ),
    ]
