# Generated by Django 6.0.7 on 2026-07-27 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, verbose_name='اپلیکیشن')),
                ('model_name', models.CharField(max_length=100, verbose_name='مدل')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شناسه رکورد')),
                ('object_name', models.CharField(max_length=255, verbose_name='نام رکورد')),
                ('action', models.CharField(choices=[('create', 'ثبت'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=10, verbose_name='عملیات')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='اطلاعات قبلی')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='اطلاعات جدید')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '📜 لاگ سیستم',
                'verbose_name_plural': '📜 لاگ\u200cهای سیستم',
                'ordering': ('-created_at',),
            },
        ),
    ]
