# Generated by Django 6.0.7 on 2026-07-23 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('about', 'درباره ما'), ('history', 'تاریخچه شرکت'), ('financial', 'اطلاعیه\u200cها و گزارشات مالی'), ('shareholder', 'امور سهام'), ('governance', ' اعضاء کمیته ها'), ('vision', 'چشم\u200cانداز و مأموریت\u200cها'), ('sustainability', 'گزارش\u200cهای حاکمیت شرکت'), ('certificate', 'گواهینامه\u200cها و استانداردها')], help_text='هر نوع بخش فقط یک\u200cبار قابل تعریف است', max_length=30, unique=True, verbose_name='نوع بخش')),
                ('is_published', models.BooleanField(default=True, help_text='در صورت غیرفعال بودن، این بخش در سایت نمایش داده نمی\u200cشود', verbose_name='وضعیت انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'بخش محتوای شرکتی',
                'verbose_name_plural': 'بخش\u200cهای محتوای شرکتی',
            },
        ),
        migrations.CreateModel(
            name='CorporateStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(help_text='مثال: تعداد محصولات، تعداد کشورها و ...', max_length=255, verbose_name='عنوان آمار فارسی')),
                ('title_en', models.CharField(help_text='مثال: تعداد محصولات، تعداد کشورها و ...', max_length=255, verbose_name='عنوان آمار انگلیسی')),
                ('value', models.PositiveIntegerField(verbose_name='عدد')),
                ('suffix', models.CharField(blank=True, help_text='مانند: K ، + ، % (اختیاری)', max_length=10, verbose_name='پسوند')),
                ('icon_svg', models.FileField(blank=True, help_text='فایل SVG با پس\u200cزمینه شفاف', null=True, upload_to='corporate/icons/', verbose_name='آیکن SVG')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'آمار عددی',
                'verbose_name_plural': 'آمارهای عددی',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name_fa', models.CharField(help_text='مثال: فروش، پشتیبانی، منابع انسانی', max_length=100, verbose_name='نام دپارتمان (فارسی)')),
                ('department_name_en', models.CharField(help_text='Example: Sales, Support, Human Resources', max_length=100, verbose_name='نام دپارتمان (انگلیسی)')),
                ('phone_1', models.CharField(max_length=20, verbose_name='شماره تماس اصلی')),
                ('phone_2', models.CharField(blank=True, help_text='در صورت وجود وارد شود', max_length=20, verbose_name='شماره تماس جایگزین')),
                ('email', models.EmailField(blank=True, help_text='example@company.com', max_length=254, verbose_name='ایمیل دپارتمان')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'شماره تماس دپارتمان',
                'verbose_name_plural': 'شماره تماس دپارتمان\u200cها',
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='FollowUsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: اینستاگرام، لینکدین، تلگرام', max_length=50, verbose_name='نام شبکه اجتماعی')),
                ('url', models.URLField(help_text='آدرس کامل صفحه شبکه اجتماعی', validators=[django.core.validators.URLValidator()], verbose_name='آدرس لینک')),
                ('svg_icon', models.FileField(help_text='فقط فایل SVG آپلود شود', upload_to='icons/social/', verbose_name='آیکن شبکه اجتماعی (SVG)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'لینک شبکه اجتماعی',
                'verbose_name_plural': 'لینک\u200cهای شبکه اجتماعی',
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='GroupCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('logo', models.ImageField(help_text='ترجیحاً با پس\u200cزمینه شفاف', upload_to='group_companies/logos/', verbose_name='لوگوی شرکت')),
                ('website', models.URLField(blank=True, help_text='در صورت نیاز می\u200cتوانید بدون https وارد کنید', verbose_name='آدرس وب\u200cسایت')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'شرکت هم\u200cگروه',
                'verbose_name_plural': 'شرکت\u200cهای هم\u200cگروه',
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام کامل پروژه انجام شده', max_length=255, verbose_name='نام پروژه')),
                ('svg_icon', models.FileField(help_text='فایل SVG با پس\u200cزمینه شفاف', upload_to='projects/icons/', verbose_name='آیکون پروژه (SVG)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='عدد کوچکتر زودتر نمایش داده می\u200cشود', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='در صورت غیرفعال بودن در سایت نمایش داده نمی\u200cشود', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cهای انجام شده',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteMainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name_ena', models.CharField(blank=True, max_length=255, null=True, verbose_name='طراحی شده توسط (انگلیسی)')),
                ('designer_name_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name=' طراحی شده توسط (فارسی)')),
                ('designer_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='طراحی شده توسط (انگلیسی)')),
                ('name_company_p1_fa', models.CharField(verbose_name='نام شرکت فارسی قسمت اول')),
                ('name_company_p2_fa', models.CharField(verbose_name='نام شرکت فارسی قسمت دوم')),
                ('name_company_p1_en', models.CharField(blank=True, null=True, verbose_name='نام شرکت انگلیسی قسمت اول')),
                ('name_company_p2_en', models.CharField(blank=True, null=True, verbose_name='نام شرکت انگلیسی قسمت دوم')),
                ('slogan_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار شرکت (فارسی)')),
                ('slogan_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار شرکت (انگلیسی)')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='site/logos/', verbose_name='لوگوی هدر')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='site/logos/', verbose_name='لوگوی فوتر')),
                ('sidebar_logo', models.ImageField(blank=True, null=True, upload_to='site/logos/', verbose_name='لوگوی سایدبار')),
                ('phone_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس 2')),
                ('phone_3', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس 3')),
                ('phone_4', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس 4')),
                ('phone_5', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس 5')),
                ('phone_security_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس 1')),
                ('phone_security_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس 2')),
                ('phone_security_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس 3')),
                ('email_security', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل رسمی حراست')),
                ('fax_security', models.CharField(blank=True, max_length=20, null=True, verbose_name='فکس')),
                ('suport_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره پشتیبانی')),
                ('fax_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='فکس 1')),
                ('fax_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='فکس 2')),
                ('fax_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='فکس 3')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل رسمی')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('address_fa', models.TextField(blank=True, null=True, verbose_name='آدرس کامل فارسی')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='آدرس کامل انگلیسی')),
                ('work_days_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='روز کاری فارسی')),
                ('work_days_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='روز کاری انگلیسی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ساختار سایت',
                'verbose_name_plural': 'اطلاعات اصلی سایت',
            },
        ),
        migrations.CreateModel(
            name='AboutYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='مثال: 37', verbose_name='سابقه تأسیس')),
                ('section', models.OneToOneField(limit_choices_to={'section_type': 'about'}, on_delete=django.db.models.deletion.CASCADE, related_name='about_year', to='app_reports.corporatesection', verbose_name='بخش درباره ما')),
            ],
            options={
                'verbose_name': 'سابقه تأسیس',
                'verbose_name_plural': 'سابقه تأسیس',
            },
        ),
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان آیتم فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان آیتم انگلیسی')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('section', models.ForeignKey(limit_choices_to={'section_type': 'about'}, on_delete=django.db.models.deletion.CASCADE, related_name='about_items', to='app_reports.corporatesection', verbose_name='بخش درباره ما')),
            ],
            options={
                'verbose_name': 'آیتم درباره ما',
                'verbose_name_plural': 'آیتم\u200cهای درباره ما',
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='CorporateText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(help_text='عنوانی که در نسخه فارسی سایت نمایش داده می\u200cشود', max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(help_text='عنوان این بخش در نسخه انگلیسی سایت', max_length=255, verbose_name='عنوان انگلیسی')),
                ('content_fa', models.TextField(help_text='محتوای کامل فارسی این بخش', verbose_name='متن فارسی')),
                ('content_en', models.TextField(help_text='محتوای کامل انگلیسی این بخش', verbose_name='متن انگلیسی')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='عدد کوچکتر زودتر نمایش داده می\u200cشود', verbose_name='ترتیب نمایش')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='app_reports.corporatesection', verbose_name='بخش مربوطه')),
            ],
            options={
                'verbose_name': 'بلاک متنی',
                'verbose_name_plural': 'بلاک\u200cهای متنی',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CorporateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='تصویر مرتبط با این بلاک متنی', upload_to='corporate/images/', verbose_name='تصویر')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش تصویر')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_reports.corporatetext', verbose_name='بلاک متنی مربوطه')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CorporateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوانی که کاربر در سایت مشاهده می\u200cکند', max_length=255, verbose_name='عنوان فایل')),
                ('file', models.FileField(upload_to='corporate/attachments/', verbose_name='فایل پیوست')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app_reports.corporatetext', verbose_name='بلاک متنی مربوطه')),
            ],
            options={
                'verbose_name': 'پیوست',
                'verbose_name_plural': 'پیوست\u200cها',
                'ordering': ['display_order'],
            },
        ),
    ]
