# Generated by Django 6.0.7 on 2026-07-31 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
