# Generated by Django 6.0.7 on 2026-07-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام کامل پروژه انجام شده', max_length=255, verbose_name='نام پروژه')),
                ('svg_icon', models.FileField(help_text='فایل SVG با پس\u200cزمینه شفاف', upload_to='projects/icons/', verbose_name='آیکون پروژه (SVG)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='عدد کوچکتر زودتر نمایش داده می\u200cشود', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='در صورت غیرفعال بودن در سایت نمایش داده نمی\u200cشود', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cهای انجام شده',
                'ordering': ['display_order'],
            },
        ),
    ]
