# Generated by Django 6.0.7 on 2026-07-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaininfo',
            name='designer_name_ena',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='طراحی شده توسط (انگلیسی)'),
        ),
    ]
