# Generated by Django 6.0.7 on 2026-07-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuslink',
            name='svg_icon',
            field=models.FileField(help_text='فقط فایل SVG آپلود شود', upload_to='social/icons', verbose_name='آیکن شبکه اجتماعی (SVG)'),
        ),
    ]
