# Generated by Django 6.0.7 on 2026-07-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaininfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی (Latitude)'),
        ),
        migrations.AddField(
            model_name='sitemaininfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی (Longitude)'),
        ),
    ]
