# Generated by Django 6.0.7 on 2026-07-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0002_alter_followuslink_svg_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuslink',
            name='svg_icon',
            field=models.FileField(help_text='فقط فایل SVG آپلود شود', upload_to='icons/social/', verbose_name='آیکن شبکه اجتماعی (SVG)'),
        ),
        migrations.DeleteModel(
            name='CorporateImage',
        ),
    ]
