# Generated by Django 6.0.7 on 2026-08-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0002_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaininfo',
            name='company_activity_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='فعالیت شرکت (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='sitemaininfo',
            name='company_activity_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='فعالیت شرکت (فارسی)'),
        ),
    ]
