# Generated by Django 6.0.7 on 2026-08-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0003_sitemaininfo_company_activity_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemaininfo',
            name='company_activity_en',
        ),
        migrations.RemoveField(
            model_name='sitemaininfo',
            name='company_activity_fa',
        ),
    ]
