import hashlib
import platform
import shutil
import zipfile
from pathlib import Path

import django
from django.conf import settings
from django.utils import timezone

from .models import Backup


class BackupService:
    """
    ایجاد نسخه پشتیبان کامل پروژه
    (SQLite + Media)
    """

    KEEP_LAST_BACKUPS = 30

    def __init__(self):

        self.project_root = Path(settings.BASE_DIR)

        self.backup_root = self.project_root / "backup"
        self.temp_root = self.backup_root / "temp"

        self.backup_root.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.temp_root.mkdir(
            parents=True,
            exist_ok=True,
        )

    ########################################################
    # Create Backup
    ########################################################

    def create_backup(self):

        timestamp = timezone.localtime().strftime(
            "%Y_%m_%d_%H_%M_%S"
        )

        backup_name = f"backup_{timestamp}"

        work_dir = self.temp_root / backup_name

        database_dir = work_dir / "Database"
        media_dir = work_dir / "Media"
        info_dir = work_dir / "Information"

        database_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        media_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        info_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        try:

            self._backup_database(database_dir)

            self._backup_media(media_dir)

            self._create_info_file(info_dir)

            zip_path = self._create_zip(
                backup_name=backup_name,
                source_dir=work_dir,
            )

            Backup.objects.create(
                file_name=zip_path.name,
                file_size=zip_path.stat().st_size,
                checksum=self._calculate_checksum(
                    zip_path,
                ),
            )

            self._cleanup_old_backups()

            return zip_path

        finally:

            shutil.rmtree(
                work_dir,
                ignore_errors=True,
            )

    ########################################################
    # SQLite Database
    ########################################################

    def _backup_database(self, database_dir):

        database_file = Path(
            settings.DATABASES["default"]["NAME"]
        )

        if not database_file.is_file():

            raise FileNotFoundError(
                "SQLite database file not found."
            )

        shutil.copy2(
            database_file,
            database_dir / database_file.name,
        )

    ########################################################
    # Media
    ########################################################

    def _backup_media(self, media_dir):

        media_root = Path("/home/nkavoshc/public_html/media")

        if media_root.exists() and media_root.is_dir():
            shutil.copytree(
                media_root,
                media_dir,
                dirs_exist_ok=True,
            )

    ########################################################
    # Backup Information
    ########################################################

    def _create_info_file(self, info_dir):

        database_file = Path(
            settings.DATABASES["default"]["NAME"]
        )

        media_root = Path(settings.MEDIA_ROOT)

        media_files = (
            sum(
                1
                for item in media_root.rglob("*")
                if item.is_file()
            )
            if media_root.is_dir()
            else 0
        )

        info = f"""
==============================
Backup Information
==============================

Project:
{settings.ROOT_URLCONF}

Created At:
{timezone.localtime():%Y-%m-%d %H:%M:%S}

Python:
{platform.python_version()}

Django:
{django.get_version()}

Database:
SQLite

Database File:
{database_file.name}

Database Size:
{database_file.stat().st_size if database_file.exists() else 0} Bytes

Media Exists:
{"Yes" if media_root.is_dir() else "No"}

Media Files:
{media_files}

Generated By:
BackupService
"""

        (
            info_dir / "backup_info.txt"
        ).write_text(
            info.strip(),
            encoding="utf-8",
        )

    ########################################################
    # Zip
    ########################################################

    def _create_zip(
        self,
        backup_name,
        source_dir,
    ):

        zip_path = (
            self.backup_root /
            f"{backup_name}.zip"
        )

        with zipfile.ZipFile(
            zip_path,
            mode="w",
            compression=zipfile.ZIP_DEFLATED,
            compresslevel=9,
        ) as zip_file:

            for file in source_dir.rglob("*"):

                if file.is_file():

                    zip_file.write(
                        filename=file,
                        arcname=file.relative_to(
                            source_dir,
                        ),
                    )

        return zip_path

    ########################################################
    # SHA-256
    ########################################################

    @staticmethod
    def _calculate_checksum(file_path):

        sha256 = hashlib.sha256()

        with file_path.open("rb") as file:

            while chunk := file.read(8192):
                sha256.update(chunk)

        return sha256.hexdigest()

    ########################################################
    # Cleanup
    ########################################################

    def _cleanup_old_backups(self):
        """
        فقط آخرین نسخه‌های پشتیبان نگهداری می‌شوند.
        """

        backups = Backup.objects.order_by(
            "-created_at",
        )

        for backup in backups[
            self.KEEP_LAST_BACKUPS:
        ]:

            backup.delete()